import { Request, Response, NextFunction } from 'express';
import { AlertRepository } from '../repositories/alert.repository';
import { CronService } from '../services/cron.service';

export class AlertController {
  private readonly alertRepo: AlertRepository;

  constructor(private readonly cronService: CronService) {
    this.alertRepo = new AlertRepository();
  }

  /**
   * GET /api/v1/alerts
   * Active restocking alerts generated by cron or inventory events
   */
  getActiveAlerts = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const alerts = await this.alertRepo.getActiveAlerts();
      res.json({
        success: true,
        data: alerts,
        meta: {
          count: alerts.length,
          critical: alerts.filter((a) => a.severity === 'CRITICAL').length,
          warning: alerts.filter((a) => a.severity === 'WARNING').length,
        },
      });
    } catch (error) {
      next(error);
    }
  };

  /**
   * POST /api/v1/cron/trigger
   * Force execution of the 60-second stock evaluation job immediately
   */
  triggerCron = async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const result = await this.cronService.evaluateStockNow();
      res.json({
        success: true,
        message: 'Evaluación de inventario ejecutada manualmente',
        data: result,
      });
    } catch (error) {
      next(error);
    }
  };

  /**
   * GET /api/v1/cron/status
   * Retrieve node-cron scheduler telemetry and execution history
   */
  getStatus = async (req: Request, res: Response): Promise<void> => {
    const status = this.cronService.getStatus();
    res.json({
      success: true,
      data: status,
    });
  };
}
